# Development overrides for Docker Compose
version: '3.8'

services:
  # Development database configuration
  database:
    ports:
      - "5432:5432"  # Expose database port for development tools
    environment:
      POSTGRES_DB: geoquiz_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  # Development backend configuration
  backend:
    build:
      target: runtime
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=database;Port=5432;Database=geoquiz_dev;Username=dev_user;Password=dev_password"
      JwtSettings__SecretKey: "development-secret-key-change-in-production-this-must-be-at-least-32-characters-long"
      JwtSettings__ExpirationMinutes: 1440  # 24 hours for development
      CorsSettings__AllowedOrigins__0: "http://localhost:3000"
      CorsSettings__AllowedOrigins__1: "http://localhost:3001"
      SecuritySettings__EnforceHttps: false
      Serilog__MinimumLevel__Default: Debug
    ports:
      - "5000:5000"
    volumes:
      # Mount source code for hot reload (if using dotnet watch)
      - ../../backend/GeoQuizApi:/app/source:ro
      - backend_dev_logs:/app/logs
    command: ["dotnet", "GeoQuizApi.dll"]

  # Development frontend configuration
  frontend:
    build:
      args:
        REACT_APP_API_URL: http://localhost:5000/api
    environment:
      NGINX_HOST: localhost
    ports:
      - "3000:80"
    volumes:
      # For development, you might want to mount source for live updates
      # - ../../src:/app/src:ro
      # - ../../public:/app/public:ro
      - frontend_dev_cache:/tmp/nginx

# Development volumes
volumes:
  postgres_dev_data:
    driver: local
    name: geoquiz_postgres_dev_data
  backend_dev_logs:
    driver: local
    name: geoquiz_backend_dev_logs
  frontend_dev_cache:
    driver: local
    name: geoquiz_frontend_dev_cache